spring:
  application:
    name: dna-tools-api
  datasource:
    url: jdbc:mysql://localhost:3306/dna
    username: dna_user
    password: dna1412
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: dna-tools-jwt-secret-key-should-be-at-least-32-bytes!!
  expiration: 3600000 # 1시간

file:
  upload:
    image-dir: E:/dna/uploads/images

app:
  image:
    base-url: http://localhost:8080
