spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: dna-tools-api
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/dna}
    username: ${DB_USERNAME:dna_user}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1시간

file:
  upload:
    image-dir: ${IMAGE_DIR:./uploads/images}

app:
  image:
    base-url: ${IMAGE_BASE_URL:}

logging:
  level:
    root: INFO
    com.dna.tools: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/dna-tools.log
    max-size: 10MB
    max-history: 30
